version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "19:35"
      timezone: "Asia/Tokyo"
    reviewers:
      - "Umekawa"
