version: "3.8"
services:
  sample:
    image: $REGISTRY/$DOCKER_REPOSITORY:$DOCKER_TAG
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SAMPLE_ENV: SAMPLE
    volumes:
      - ./sample_folder:/app/sample_folder
networks:
  default:
