version: "3.8"
services:
  sample:
    image: sample_image:master
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SAMPLE_ENV: SAMPLE
    volumes:
      - ./sample_folder:/app/sample_folder
networks:
  default:
