name: Check Environment

on:
  push:
    branches:
      - check-env
  workflow_dispatch:

permissions:
  contents: read
  packages: read

env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  DOCKER_CACHE_TAG: master
  DOCKER_REPOSITORY: umekawa/github-actions-sample
  DOCKER_TAG: check_env
  REGISTRY: ghcr.io

jobs:
  use_cache_sample:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry (GitHub Container Registry)
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        id: docker_build
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: ${{ env.REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ env.DOCKER_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha
            ${{ env.REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ env.DOCKER_CACHE_TAG }}
          cache-to: type=gha,mode=max
      - name: Check Env
        run: >
          docker compose -f docker-compose.yml run
          sample bash -c "env"
        env:
          SAMPLE_TEXT: sample_text
